open-dynamic-robot-initiative/trifinger_simulation

- README.md
- docs/index.rst
fix installation instructions link and citations in readme
> fix link to installation instructions and citation in readme

- demos/catkin/demo_robot_interface.py
- demos/demo_control.py
- python/trifinger_simulation/finger_types_data.py
- python/trifinger_simulation/real_finger.py
- python/trifinger_simulation/sim_finger.py
- scripts/pybullet_backend.py
- tests/catkin/test_pybullet_backend.py
- tests/test_determinism.py
- tests/test_reset_joints.py
- tests/test_robot_equivalent_interface.py
We do not need these two finger type names anymore... they were creating confusion, so removed them.
[//]: # "Explain how you tested your changes"
Ran all the unit tests for python and the changed demo files.
> removed deprecated single and tri as valid finger types

- README.md
- docs/conf.py
fixes installation instructions section in readme
by looking at the readme preview
> fix installation instructions section in readme

- python/trifinger_simulation/camera.py
Contrary to my assumption, the "BG" in OpenCV's "BayerBG" does not refer
to the first row, first two columns of the Bayer pattern but to second
row, second and third column (see
https://docs.opencv.org/3.2.0/de/d25/imgproc_color_conversions.html).
So to get a pattern that can correctly be reconstructed with "BayerBG",
red and blue need to be swapped.
By converting the generated images back to BGR using the same function as for the images of the real cameras.
> Fix generation of simulated Bayer images

- python/trifinger_simulation/tasks/move_cube.py
Increase episode length to 2 min at 1 kHz for challenge phase 2
In combination with https://github.com/open-dynamic-robot-initiative/robot_fingers/pull/72.
> Increase episode length to 2min for challenge phase 2

- python/trifinger_simulation/trifinger_platform.py
- python/trifinger_simulation/trifingerpro_limits.py
Add module with TriFingerPro limits.  By having this in a separate file it can be used more generally.
With this, the `spaces` attribute could probably be removed completely from `TriFingerPlatform`. However, I want to avoid unnecessary changes like this at the moment, so for now keep it there.
Also changed some imports from the same package to relative imports as this improves auto-completion in my editor (this way it finds the files without the need to install the package).
By running demo_trifinger_platform.py
> Move robot limits to separate file

- tests/test_parallel_instances.py
for me, changing the action2 to be applied to lie within the ranges as mentioned in the action space in `trifingerpro_limits.py` fixed the unittest, which was failing in its earlier state.
by running the mentioned unit test
> fix unittest for parallel instances

- scripts/pybullet_backend.py
The default position is shifted to the side, so explicitly set it to the
centre of the arena, to match better with the real system.
Executing a challenge job locally in simulation.
> Spawn the cube in the centre of the arena

- tests/catkin/test_pybullet_backend.cpp
The old goal positions in the unit test were for TriFingerOne and are
not feasible for TriFingerPro.  Replace with other positions that can be
reached by TriFingerPro.
Also print the actual positions in case of failure for easier debugging.
By running the unit tests.
> fix unit test for TriFingerPro

- example/example_pushing_training_env.py
- python/trifinger_simulation/collision_objects.py
- python/trifinger_simulation/gym_wrapper/envs/cube_env.py
- python/trifinger_simulation/tasks/move_cube.py
- python/trifinger_simulation/trifinger_platform.py
- python/trifinger_simulation/visual_objects.py
- scripts/pybullet_backend.py
- tests/test_cube_env.py
- tests/test_tasks_move_cube.py
Change the manipulation object from the 6.5cm cube to the 2x2x8cm cuboid.  This is needed for phase 3 of the challenge.
To reduce the amount of necessary changes during the challenge, I did it in a slightly hacky way by simply replacing the current cube with the cuboid (which is still called "cube" in many places, though).  This way there is no change on the API and the way thinks are executed.  If you think that's bad for master, we can create a separate "challenge" branch.
By running `demo_random_policy.py` and `pybullet_backend.py`.
> Use small Cuboid instead of Cube

- python/trifinger_simulation/tasks/move_cube.py
- tests/test_tasks_move_cube.py
Ignore rotation around the long axis of the cuboid (y-axis) as the
object tracking is not so reliable on this axis.
Add a unit test to verify this.
By running the unit tests.
> Reward level 4: Ignore rotation around y-axis

- python/trifinger_simulation/tasks/move_cube.py
- python/trifinger_simulation/tasks/move_cuboid.py
When sampling initial poses for the cube/cuboid (object on ground,
random yaw angle), also randomise which face of the object is pointing
upwards.  With the old version, it was always the same which became
apparent now when using the multi-colour cube model.
By sampling random poses and visualising them via pyBullet.
> Random face up when sampling initial cube poses

- .github/workflows/style_checker.yml
Since black is now configured via pyproject.toml, it shouldn't be
necessary anymore to set custom arguments on the GitHub workflow.
> GitHub: Remove specific config from black workflow

- python/trifinger_simulation/camera.py
- tests/test_camera.py
Add a `dump` method to `CameraParameters` to store the parameters to a YAML file.
By running the corresponding unit test and by using it.
> Add CameraParameters.dump to save parameter file

- python/trifinger_simulation/visual_objects.py
- scripts/trifingerpro_model_test.py
- Remove the body of an `ObjectMarker` from the simulation upon destruction of the marker instance.  This is the same as what is already done for the collision objects.
- Add a simple script to test the TriFingerPro model.
By running the added script.
> Remove ObjectMarkers on destruction & test robot model

- docs/getting_started/installation.rst
- docs/simreal/simwithreal.rst
- environment.yml
- package.xml
- setup.cfg
- setup.py
There is no C++ code here anymore, so converting this into a pure Python
package should make it easier to use it stand-alone, e.g. with conda.
Also push versions in environment.yml to match with the recent Singularity image and update installation instructions 
By trying both the colon workspace and the conda environment, running one of the demo scripts.
> Convert to ament_python package

- python/trifinger_simulation/collision_objects.py
- python/trifinger_simulation/trifinger_platform.py
Add class `ColoredCubeV2` which provides the same interfaces as the `Cube` class but loads the object and
its properties from the cube_v2 URDF file.  Use it in `TriFingerPlatform` instead of the mono-colour cube.
Add an abstract class `BaseCollisionObject` for this.
By running `demo_trifinger_platform.py`.
> Add ColoredCubeV2 collision object

- demos/demo_control.py
- demos/demo_inverse_kinematics.py
- python/trifinger_simulation/finger_types_data.py
- python/trifinger_simulation/sim_finger.py
- python/trifinger_simulation/trifinger_platform.py
- scripts/check_position_control_accuracy.py
- scripts/playback_data.py
- scripts/profiling.py
- scripts/trifingerpro_model_test.py
- To avoid confusion for users that are switching between simulation and real robot, set the default step size of the simulation to 0.001 to match the real robot.
- Use different PD gains based on the finger type and tune the gains for (Tri)FingerPro.  The gains are tuned manually using check_position_control_accuracy.py (which has been modified a bit for this).  With these gains a mean error of [0.0095 0.01435 0.0039] is achieved when using a step size of 0.001.
- To make tuning gains for TriFingerPro easier, enable the use of a single FingerPro in the Simulation.
- To make tuning easier (but also because it might be useful in other cases), add an argument `robot_position_offset` to `SimFinger` which allows changing the robot position (e.g. to modify the distance between fingers and …
> Set default time_step to 0.001 and tune PD gains for FingerPro

- docs/getting_started/installation.rst
- environment.yml
- package.xml
- pyproject.toml
- requirements.txt
- setup.py
With all the dependencies specified in the setup.py, the package can be
installed directly with pip, so there is no need for conda anymore.
Addresses part of #57 
By installing it via `pip install .` and testing the installation by running some of the demos.
I did not yet verify if this change causes any trouble when still using conda (which should still be supported, even if not needed anymore).
> Add dependencies to setup.py

- python/trifinger_simulation/tasks/move_cube/__init__.py
- tests/test_tasks_move_cube.py
To make the code a bit more flexible, also accept goals of type `dict`
in `validate_goal` and `evaluate_state` and convert them to a `Pose`
internally.
Using the unit tests added in this PR.
> tasks.move_cube: Accept dict-goal

- python/trifinger_simulation/camera.py
Height and width were mixed up when cropping the distorted points to the image area, resulting in some part of the image missing when having a non-square aspect ratio.
using demo_cameras.py (see screenshot above)
> fix: Flipped dimensions when cropping distorted image

- python/trifinger_simulation/sim_finger.py
Change initial camera pose and colours of stages for single finger and TriFingerEdu.  See individual commits for details.
By running the simulation with different finger types.
> Change camera pose in GUI and colours of stages

- .github/workflows/git.yml
Fixup/squash commits (`git commit --fixup`/`git commit --squash`) can be
very useful during development and code review but they should be
cleaned up before merging into master.
This GitHub action checks for existence of such commits, so merging can
be blocked automatically.
In this pull request.
> Add GitHub Action to block fixup commit

- .github/workflows/docs.yml
- docs/index.rst
- docs/requirements.txt
- Use recently released version 2 of sphinx-notes/pages.
- Include package requirements in the doc requirements (otherwise build
fails)
- Add current date at the bottom of the start page, so it is easier to
verify if the documentation was updated.
> chore: Update documentation build

- python/trifinger_simulation/sim_finger.py
- tests/test_sim_finger.py
As pointed out in https://github.com/rr-learning/CausalWorld/issues/101 `np.clip` got significantly slower in NumPy versions >=1.17.
The best workaround currently seems to be to use the internal `np.core.umath.clip` instead (see https://github.com/numpy/numpy/issues/14281).
`np.core.umath.clip` does not exist in versions <1.17 so in this case we fall back to `np.clip` (which is okay because in these versions `np.clip` was still good).
At least on my laptop, this change speeds up the simulation by around 13%.
I also moved the computation of the safe torque to a static method that doesn't depend on …
> Use np.core.umath.clip instead of np.clip

- setup.py
- tests/test_cube_env.py
It turned out that gym versions >=0.20 cause some tests to fail.  So
until this is resolved, fix the version to 0.18.0 (which also matches
with what we are using in our Singularity images).
By running unit tests.
> Pin gym version to 0.18.0

- demos/demo_plain_torque_control.py
- scripts/check_position_control_accuracy.py
- scripts/trifingerpro_model_test.py
- trifinger_simulation/finger_types_data.py
- trifinger_simulation/sim_finger.py
For each finger type specify its default initial position in the
finger_types_data module (using the same values as in the configuration
of the real robots).
This is ensures that the fingers are not stuck in the ground upon
initialisation, which is the case for some of the robots if initialised
to all-zero positions.
Remove redundant initialisation from some of the scripts.
By running unit tests and some demo scripts.
> Set initial position based on finger type

- tests/test_trifinger_platform.py
- trifinger_simulation/trifinger_platform.py
- Remove timestamp from ObjectPose (it has already been removed on the real robot some time ago).
- Simulate delay of camera observations (to account for time needed for object detection on the real system).
This is an alternative implementation to #83.  The delay is implemented by using two different trigger times:  `_next_camera_trigger_t` which marks the next time step at which a new observation is queried from the cameras (aka images are rendered) and `_next_camera_observation_read_t` which marks the time at which the observation that is provided to the user gets updated with the observation from the last trigger.
Also added unit tests to make sure the timing works correctly.
By running the unit tests. …
> Simulate delay of camera observations

- CHANGELOG
- tests/test_determinism.py
- trifinger_simulation/gym_wrapper/finger_spaces.py
See commits for details.
By running unit tests.
> Set gym space dtypes to float64 and fix failing test

- .github/workflows/docs.yml
Use the new (beta) feature of GitHub to deploy the documentation to Pages using an artifact/action instead of pushing to a separate "gh-pages" branch.
Through this PR.
> chore: Deploy docs via action instead of using branch.

- trifinger_simulation/gym_wrapper/envs/trifinger_reach.py
The `seed()` method has been removed from Env in recent versions of gym (instead the seed can be passed to `reset()`).
Since calling it without arguments anyway seems pointless, just remove the call altogether.
Unit tests
> fix: Do not call gym.Env.seed()

- setup.cfg
Apparently setup.cfg does not support comments at the end of a line. Instead, the comment needs to be in its own line.
This had caused an error when running tests via `colcon test`.
> fix: Comment in setup.cfg

- tests/test_tasks_move_cuboid.py
- trifinger_simulation/tasks/move_cuboid.py
It can occasionally happen that due to float inaccuracy the dot product
returns something like 1.0000000000000002 instead of 1.0.  Since it is >
1, this causes arccos to return nan, thus failing the whole calculation.
To avoid this, round a little bit (10 decimal digits should still be
accurate enough) to get rid of the error.
While debugging the issue, I also converted the corresponding test to use pytest instead of unittest (no changes to the actual tests were done).
By running the tests in another PR (where it was failing).
> Fix numerical issue in move_cuboid task

- .github/workflows/build_pr.yml
- .github/workflows/docs.yml
- .github/workflows/git.yml
- .github/workflows/lint.yml
- .github/workflows/pr_todo_checks.yml
- .github/workflows/test.yml
- CHANGELOG
- demos/demo_control.py
- demos/demo_load_gym_env.py
- scripts/playback_data.py
- scripts/plot_tip_position_trajectories.py
- tests/test_camera.py
- tests/test_determinism.py
- trifinger_simulation/pinocchio_utils.py
- trifinger_simulation/sim_finger.py
- trifinger_simulation/tasks/move_cube/replay_action_log.py
- trifinger_simulation/tasks/move_cube/run_evaluate_policy.py
Mark the pinocchio_utils module as deprecated (to be removed in a future release).  The module has been moved to the robot_properties_fingers package and will be maintained there from now on.
For now keep the implementation here as robot_properties_fingers is currently not pip-installable (so removing it would be a problem for users who use the pip-installation of trifinger_simulation).  It can be removed as soon as robot_properties_fingers is converted to pure Python and published on PyPI (which is a long-standing TODO anyway).
Ran a demo script that uses the module.
[//]: # "Link other open pull request here that need to be merged first."
[//]: # "Remove this section if it does not apply."
> Add deprecation warning to pinocchio_utils

- .github/workflows/docs.yml
- Rename the documentation workflow from "Pages" to "Documentation" so its more obvious what it is about.
- Add workflow_dispatch event so it can be triggered manually.  Add an option to disable publishing in this case, to allow testing only the build (useful for branches before merging).
> chore: Add workflow_dispatch to documentation build workflow

- .github/workflows/doc_test.yml
- .github/workflows/docs.yml
- docs/getting_started/installation.rst
- requirements.txt
- Update the documentation workflow.  The new sphinx-notes/pages action now directly publishes on its own, so the whole workflow can be simplified.
- Do not require explicit versions of dependencies (hopefully this fixes a build issue on master)
~~Through "workflow_dispatch" trigger of the documentation workflow.~~
Not working as desired due to environment stuff.  Will merge and see what happens...
> Fix Documentation Build

- .github/workflows/doc_test.yml
- .github/workflows/docs.yml
It seems the issue due to which the package was checked out to a sub-directory does not exist anymore with v3 of the pages action, so we can get rid of the workaround and make the workflow much simpler.
Also fix the arguments of the pages action, which have changed a bit in v3.
> Fix and simplify documentation build workflows

- trifinger_simulation/camera.py
Add `get_width`/`get_height` to the Camera classes and store the original camera matrix in CalibratedCamera.  This is to make it easier to access this information in the PyBullet driver implemented in trifinger_cameras.
> get_width/height of cameras & save original camera matrix

- .github/workflows/lint.yml
- .github/workflows/test.yml
- Bump actions/checkout and setup-python to latest versions.
> chore: Bump versions in GitHub workflows

- setup.cfg
`script-dir` and `install-scripts` are deprecated, one should use `script_dir`/`install_scripts` now.
Changing this silences a warning and will probably make the package more future-proof.
Build the package with colcon and ran a demo script to test.
> build: use script_dir instead of script-dir

- trifinger_simulation/tasks/move_cuboid.py
Mypy complained about this because the input is a numpy type rather than
a native Python type.
It was still working as expected but since changing `min` to `np.min` is
trivial and makes the type checker happy, let's simply do that.
This should not change the behaviour of the code in any way.
> fix: Use np.min to avoid mypy error

- setup.cfg
There are issues with NumPy 2.  Until they are resolved, pin the version to <2.
> fix: Require NumPy <2

- conda_activate_trifinger_simulation.sh
- docs/getting_started/installation.rst
- docs/requirements.txt
- environment.yml
- requirements.txt
They should not be needed anymore, just use normal pip (should work, even when still using conda).
> Clean up the conda files

- CHANGELOG.md
- trifinger_simulation/camera.py
PyBullet may not use NumPy in some installations (see https://github.com/bulletphysics/bullet3/issues/4523). To make sure our code still works, catch that and convert the image accordingly.
Unit tests and by running `demo_cameras.py` in an environment where pybullet did not use numpy.
> Avoid failure if pybullet doesn't use numpy

- CHANGELOG.md
- demos/demo_cameras.py
- trifinger_simulation/camera.py
The downsampling to 270x270 is removed from trifinger_cameras, therefore, change the default resolution to 540x540 here, so it matches with the real robots.
By running demo_cameras.py
> Change default camera resolution to 540x540
