open-dynamic-robot-initiative/trifinger_simulation

docs/conf.py

this is to test if build passes on rtd

add explicit import for yt link

---

README.md

Just updated the link in the readme for the installation instructions.
by checking the link

fixed installation link in readme

---

python/trifinger_simulation/tasks/__main__.py
python/trifinger_simulation/tasks/move_cube.py

This file can be executed from anywhere using
python -m trifinger_simulation.tasks
It serves as a convenient way to call functions to sample goals and
validate files for the move_cube task.
Add a function `validate_goal_file` which validates a JSON file
specifying goal parameters for the submission system.
Through manual testing.  Should add some unit tests for validate_goal_file() later.
Side note: This will always produce that annoying "pybullet build time" print.  The tasks package does not depend on anything else in this package (not even pybullet), so we should probably move it to some other package to fix this issue.

__main__ module for tasks package and goal file validation

---

python/trifinger_simulation/camera.py

The cameras on the real robot provide their images in raw format (Bayer
BG) and need to be converted by the user.  To get the same behaviour
from the simulation, convert the rendered RGB image to a Bayer pattern
by keeping only one channel from each pixel, according to the pattern.
Also reduce the default image resolution to 270x270 as on the real
robot.
(I also added type hints, this is not yet fully working, though.  At least I did not get warnings when intentionally making type-mistakes.)
By running the simulation and visualising the images.
[//]: # "Please make sure you followed these steps …

Simulate raw camera data using Bayer pattern

---

demos/demo_control.py
demos/demo_inverse_kinematics.py
python/trifinger_simulation/gym_wrapper/envs/trifinger_push.py
python/trifinger_simulation/gym_wrapper/envs/trifinger_reach.py
python/trifinger_simulation/pinocchio_utils.py
python/trifinger_simulation/sample.py
python/trifinger_simulation/sim_finger.py
python/trifinger_simulation/trifinger_platform.py

- Make the inverse kinematics implementation finally work.
- Add a demo using it.
- Rename `PinocchioUtils` to `Kinematics` to be more descriptive.
With the new demo.

Make Inverse Kinematics work

---

example/example_pushing_training_env.py
python/trifinger_simulation/camera.py
python/trifinger_simulation/collision_objects.py
python/trifinger_simulation/sample.py
python/trifinger_simulation/sim_finger.py
python/trifinger_simulation/trifinger_platform.py
python/trifinger_simulation/visual_objects.py

Fixes propagated from rrc_simulation:
1. Enable different physics client ids for multiple processes to run parallel.
2. Tip force
Other changes:
1. Fix in the sampling method for sampling a point in the arena.
2. Make some camera params configurable.
By running all the unit tests and demos.

changes for parallelization and some minor bugs fixed

---

demos/demo_control.py
example/example_pushing_training_env.py
python/plot_tip_position_trajectories.py
python/trifinger_simulation/camera.py
python/trifinger_simulation/collision_objects.py
python/trifinger_simulation/gym_wrapper/envs/trifinger_push.py
python/trifinger_simulation/real_finger.py
python/trifinger_simulation/sample.py
python/trifinger_simulation/sim_finger.py
python/trifinger_simulation/tasks/move_cube.py
python/trifinger_simulation/visual_objects.py
tests/test_determinism.py
tests/test_loading_urdfs.py
tests/test_reset_joints.py

Reformat the whole packages Python code with `black --line-length 79 .`.
By running the unit tests

Reformat using Black

---

demos/catkin/demo_object_tracker.py
demos/catkin/demo_robot_interface.py
example/evaluate_policy.py
package.xml
python/trifinger_simulation/action.py
python/trifinger_simulation/collision_objects.py
python/trifinger_simulation/gym_wrapper/envs/cube_env.py
python/trifinger_simulation/sim_finger.py
python/trifinger_simulation/tasks/move_cube.py
python/trifinger_simulation/trifinger_platform.py
python/trifinger_simulation/visual_objects.py
scripts/replay_action_log.py
scripts/run_evaluate_policy_all_levels.py
tests/test_parallel_instances.py
tests/test_robot_equivalent_interface.py

This PR should apply all relevant changes/fixes from the rrc_simulation challenge which were not already applied here.
Running unittests and some of the demos.

Port changes and bugfixes from the rrc_simulation repo

---

include/trifinger_simulation/pybullet_driver.hpp

Change the pyBullet driver to use TriFingerPro, so we can use it for the
challenge.
On the long term, we should add an option here instead of hard-coding
this...
By running pybullet_backend.py

Use TriFingerPro in pyBullet driver

---

include/trifinger_simulation/pybullet_driver.hpp
scripts/pybullet_backend.py

Add the missing parts so pybullet_backend.py can act as a replacement of robot_fingers/trifinger_backend.py in the submission system setup.  This is need so that users can test submissions locally in simulation before sending them to the robot.
By using it in the submission system setup.

Adjust pybullet_backend.py for submission system

---

python/trifinger_simulation/robot_properties_fingers/urdf/pro/fingerpro.urdf
python/trifinger_simulation/robot_properties_fingers/urdf/pro/trifingerpro.urdf
python/trifinger_simulation/robot_properties_fingers/urdf/pro/trifingerpro_with_stage.urdf

Update robot models to state of robot_properties_fingers rev. c54301e

Update robot model

---

demos/demo_trifinger_platform.py
python/trifinger_simulation/__init__.py
python/trifinger_simulation/gym_wrapper/envs/cube_env.py
python/trifinger_simulation/trifinger_platform.py
tests/test_trifinger_platform.py

Update the `TriFingerPlatform` class according to API changes on `robot_fingers::TriFingerPlatformFrontend`.  The object pose is now included in the camera observation.
Further enable the reduced camera rate to replicate the behaviour of the real system.
By running unit tests and the corresponding demo.

Update API of TriFingerPlatform

---

python/trifinger_simulation/sim_finger.py
python/trifinger_simulation/trifingerpro_limits.py
tests/test_cube_env.py

The max. current on the robot was increased to 2.2 A, so the max. torque
increases to 0.396 Nm.
By running the unit tests.

Update the maximum torque

---

README.md

Wrap long lines in the README.

Reformat README a bit

---

python/trifinger_simulation/tasks/move_cuboid.py
tests/test_tasks_move_cuboid.py

Reset `move_cube.py` to the state of the real_robot_challenge_phase2 tag
where the object was actually the cube.  The newer version of that file
was modified for the smaller cuboid and is kept as `move_cuboid.py`.
Running the unit tests.

Restore move_cube.py for the actual cube

---

python/trifinger_simulation/data/cube_v2/cube_v2.urdf

fix cube_v2 collision shape and inertial
Loading the cube in simulation and checking for contact points with the robot.

fix cube_v2 collision shape and inertial

---

tests/test_tasks_move_cuboid.py

fix module name in move_cuboid tests
By running the tests (directly calling pytest)

fix module name in move_cuboid tests

---

.flake8
pyproject.toml

Add config for linters and formatters
By running black and flake8 in the package directory.

Add config for linters and formatters

---

python/trifinger_simulation/tasks/move_cube.py
python/trifinger_simulation/tasks/move_cube_on_trajectory.py
tests/test_tasks_move_cube_on_trajectory.py

Add a task module "move_cube_on_trajectory with methods to generate, validate and evaluate trajectories.
In move_cube.Pose: Make sure the passed position and orientation are numpy arrays.
By running the accompanying unit tests.

Implement the "move cube on trajectory" task

---

.github/workflows/lint.yml

Add GitHub Action to run mypy.

Add GitHub Action to run mypy

---

python/trifinger_simulation/tasks/move_cube/run_replay.py
python/trifinger_simulation/tasks/move_cube_on_trajectory/replay_action_log.py
scripts/check_position_control_accuracy.py

Fix mypy errors.
Via the mypy check on this PR.

Fix mypy issues

---

python/trifinger_simulation/tasks/rearrange_dice/__init__.py
python/trifinger_simulation/tasks/rearrange_dice/__main__.py
python/trifinger_simulation/tasks/rearrange_dice/test_reward.py
python/trifinger_simulation/tasks/rearrange_dice/utils.py

- Add functions to parse goals from ASCII patterns and a script for manually testing reward computation.
- Increase the tolerance a bit and add it to the goal masks.
- Make sure the rearrange_dice cost is returned as float
By using the new test script and running unit tests.

Adjustments on the rearrange_dice task

---

docs/conf.py
tests/test_camera.py
tests/test_tasks_move_cube_on_trajectory.py
tests/test_tasks_rearrange_dice.py

Fix the flake8 warnings that were revealed in #65.
By running the unit tests

fix flake8 warnings

---

docs/api/trifingerplatform.rst
python/trifinger_simulation/__init__.py

Updated the API docs of `TriFingerPlatform` which was a bit outdated.
Built docs locally.

Fix docs of TriFingerPlatform

---

demos/demo_plain_torque_control.py

This demo is supposed to be a minimal example, so keep it as simple as
possible.
by running it

Simplify the plain torque ctrl demo a bit

---

.github/workflows/test.yml

Add GitHub workflow to run tests
Through this PR.

chore: Add GitHub workflow to run tests

---

demos/demo_cameras.py

Images can be saved by setting `--save-dir` and then pressing "s" at
runtime.
Images can be saved by setting `--save-dir` and then pressing "s" at
runtime.
By running it.

demo_cameras: Add option to save images

---

scripts/screenshot_mode.py

A simple script that runs the simulation with all visualisations disabled, so it is easier to make nice screenshots.
Used it some time ago to create the screenshots for the documentation.

Add script screenshot_mode.py

---

.github/workflows/build_pr.yml
.github/workflows/test.yml

Build and run tests via colon.  This is in addition to the already existing test in test.yml that directly installs the package via pip.
Through this PR.

chore: Add PR check that builds with colon

---

CHANGELOG
trifinger_simulation/robot_properties_fingers/urdf/pro/fingerpro.urdf
trifinger_simulation/robot_properties_fingers/urdf/pro/trifingerpro.urdf
trifinger_simulation/robot_properties_fingers/urdf/pro/trifingerpro_with_stage.urdf

Taken from robot_properties_fingers commit
427200b22ee4e595cf9a3b67d935698a44eb8ef2.

fix: Update URDF files with latest version from robot_properties_fingers
